site_name: Project documentation
site_author: Egor Chernov
site_url: https://egorchernov5.github.io
nav:
  - Home: index.md
  - Labs:
    - Lab 1: Lr1/lr1-tasks.md
    - Lab 2: Lr2/lr2-tasks.md
  - PW:
      - PW 3: PW3/pw3-tasks.md
theme:
  name: lux
